// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "acl-manager": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/microservice-security/acl/rest
// --out=$(GOPATH)/src/github.com/JormungandrK/microservice-security/acl/rest
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// GetAclContext provides the acl get action context.
type GetAclContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	PolicyID string
}

// NewGetAclContext parses the incoming request URL and body, performs validations and creates the
// context used by the acl controller get action.
func NewGetAclContext(ctx context.Context, r *http.Request, service *goa.Service) (*GetAclContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := GetAclContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramPolicyID := req.Params["policyId"]
	if len(paramPolicyID) > 0 {
		rawPolicyID := paramPolicyID[0]
		rctx.PolicyID = rawPolicyID
	}
	return &rctx, err
}
