// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "acl-manager": acl TestHelpers
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/microservice-security/acl/rest
// --out=$(GOPATH)/src/github.com/JormungandrK/microservice-security/acl/rest
// --version=v1.2.0-dirty

package test
